export const FETCH_DETAILS = "item/FETCH_DETAILS";
export const FETCH_DETAILS_COMPLETED = "item/FETCH_DETAILS_COMPLETED";
export const FETCH_DETAILS_FAILED = "item/FETCH_DETAILS_FAILED";

export const FETCH_LIST = "item/FETCH_LIST";
export const FETCH_LIST_COMPLETED = "item/FETCH_LIST_COMPLETED";
export const FETCH_LIST_FAILED = "item/FETCH_LIST_FAILED";



export const POST_ITEM = "POST_ITEM";
export const POST_ITEM_COMPLETED = "POST_ITEM_COMPLETED";
export const POST_ITEM_FAILED = "POST_ITEM_FAILED";

export const DELETE_ITEM = "DELETE_ITEM";
export const DELETE_ITEM_COMPLETED = "DELETE_ITEM_COMPLETED";
export const DELETE_ITEM_FAILED = "DELETE_ITEM_FAILED";

export const ADD_ITEM ="ADD_ITEM";